chinook_project_dbt:
  outputs:

    dev:
      type: postgres
      threads: 4
      host: localhost
      port: 5432
      user: romainlejeune
      pass: pyross1992
      dbname: chinook
      schema: "public"

    prod:
      type: postgres
      threads: 4
      host: localhost
      port: 5432
      user: romainlejeune
      pass: pyross1992
      dbname: chinook
      schema:

  target: dev
